Fix the script for latest Aptoide and Android
* we need the mobile site for downloads,
  use the right user agent to access it
* use curl instead of wget to support modern Android
* allow normal Aptoide URLs and package ids as input
  and find the appropriate Aptoide download link

diff --git a/aptoide b/aptoide
--- a/aptoide
+++ b/aptoide
@@ -30,25 +30,103 @@ function main {
 	if [ "$#" -eq 1 ]; then
 		atribut $1
 	else
-		echo "Insert link:"
+		echo "Insert link or package id:"
 		read link
 		atribut $link
 	fi
 }
 
-function atribut {
-	link=$1
+# Try to find the real mobile link by normal aptoide link (https://desired-package-id.en.aptoide.com/?store_name=somestore&app_id=xxxxxxxx)
+function get_real_link_by_normal_link {
+	orig_link=$1
+	curl -o $aptoide_home_dir/.temp $orig_link 2>/dev/null
+	export returncode=$?
+	if ! [ "$returncode" = "0" ]; then
+		exit 0
+	fi
 
-	### Test if we have a valid Aptoide URL ###
-	test_url_regex=$(echo $link | sed -n 's/^\(https:\/\/.*\.store\.aptoide\.com\/\).*$/\1/p')
-	if [[ "$test_url_regex" = "" ]]; then
-		test_url_regex=$(echo $link | sed -n 's/^\(.*\.store\.aptoide\.com\/\).*$/\1/p')
-		if [[ "$test_url_regex" = "" ]]; then
-			echo "This is not a valid Aptoide URL."
+	# find the package in the downloaded given link
+	package_id=$(cat $aptoide_home_dir/.temp | sed -rn 's/.*data-package-id="(([A-Za-z]{1}[A-Za-z\d_]*\.)+[A-Za-z][A-Za-z\d_]*).*/\1/p')
+	if [[ "$package_id" = "" ]]; then
+		exit 0
+	fi
+
+	# get store name / app id from the given link
+	orig_store_name=$(echo $orig_link | sed -rn 's/.*store_name=(.+)&.*/\1/p')
+	orig_app_id=$(echo $orig_link | sed -rn 's/.*app_id=([0-9]+).*/\1/p')
+
+	echo $(get_real_link $package_id $orig_store_name $orig_app_id)
+}
+
+# Try to find the real mobile link by package id (and optional store name + app id)
+function get_real_link {
+	package_id=$1
+
+	orig_store_name=$2
+	orig_app_id=$3
+
+	# Find the app via Aptoide search API
+	curl -k -o $aptoide_home_dir/.temp "https://m.aptoide.com/phpajax/get_search.php?searchtxt=$package_id&type=apps" 2>/dev/null
+	export returncode=$?
+	if ! [ "$returncode" = "0" ]; then
+		exit 0
+	fi
+
+	# Get the link parts
+	real_link_parts=($(cat $aptoide_home_dir/.temp | sed -rn 's/.*m.(.*).store.aptoide.com\\\/app\\\/market\\\/'$package_id'\\\/([0-9]*)\\\/([0-9]*).*/\1 \2 \3/p'))
+	if [ -z "$real_link_parts" ]; then
+		exit 0
+	fi
+
+	if [ "$orig_store_name" = "" ]; then
+		# We want to download the latest version of the app, build the link url
+		real_link=$(cat $aptoide_home_dir/.temp | sed -rn 's/.*(m.'${real_link_parts[0]}'.store.aptoide.com\\\/app\\\/market\\\/'$package_id'\\\/[0-9]*\\\/[0-9]*\\\/[^\]*).*/\1/p' | sed 's/\\\//\//g')
+
+	else
+		# We want to download a specific version from a specific Store
+
+		# Get all versions of the app
+		curl -k -o $aptoide_home_dir/.temp -H "User-Agent: AptoideLite/44" "https://m.aptoide.com/list/versions/$package_id/${real_link_parts[1]}" 2>/dev/null
+		export returncode=$?
+		if ! [ "$returncode" = "0" ]; then
 			exit 0
-		else
-			link="https://$link"
 		fi
+
+		# find the link of the version we are looking fo
+		real_link=($(cat $aptoide_home_dir/.temp | sed -rn 's/.*(m.'$orig_store_name'.store.aptoide.com\/app\/market\/'$package_id'\/[0-9]*\/'$orig_app_id'\/[^"]*).*/\1/p'))
+		real_link=${real_link[0]}
+	fi
+
+	rm $aptoide_home_dir/.temp
+	echo "https://$real_link"
+}
+
+function atribut {
+	if echo $1 | grep -Eq '^(([A-Za-z]{1}[A-Za-z\d_]*\.)+[A-Za-z][A-Za-z\d_]*)$'; then
+		# We got a package id as parameter
+		link=$(get_real_link $1)
+	else
+		link=$1
+
+		### Always use https ###
+		link=$(echo $link | sed 's/http:\/\//https:\/\//g')
+
+		### Test if we have a valid Aptoide URL ###
+		test_url_regex=$(echo $link | sed -n 's/^\(https:\/\/.*\.store\.aptoide\.com\/\).*$/\1/p')
+		if [[ "$test_url_regex" = "" ]]; then
+			test_url_regex=$(echo $link | sed -n 's/^\(https:\/\/photoscan-by-google-photos\.[a-z]\{2,3\}\.aptoide\.com\).*$/\1/p')
+			if [[ "$test_url_regex" = "" ]]; then
+				echo "This is not a valid Aptoide URL."
+				exit 0
+			else
+				link=$(get_real_link_by_normal_link $link)
+			fi
+		fi
+	fi
+
+	if [[ "$link" = "" ]]; then
+		echo "Download site not found."
+		exit 0
 	fi
 
 	### We change the normal HTTP link in the HTTP link used for mobile phones ###
@@ -68,7 +146,7 @@ function atribut {
 
 	### download the html of the input url ###
 	echo "Downloading the HTML file to extract information..."
-	wget --no-check-certificate -q --user-agent="" $link_http -O $aptoide_home_dir/.$apk_package_name
+	curl -k -o $aptoide_home_dir/.$apk_package_name -H "User-Agent: AptoideLite/44" $link_http 2>/dev/null
 
 	export returncode=$?
 	if ! [ "$returncode" = "0" ]; then
@@ -118,7 +196,7 @@ function atribut {
 	##############################################
 	### Save the APK in the download directory ###
 	echo "Downloading APK file..."
-	wget -c --user-agent="" $apk_link -O "$aptoide_home_dir/$apk_package_name $version_number.apk"
+	curl -C - -H "User-Agent: AptoideLite/44" -o "$aptoide_home_dir/$apk_package_name $version_number.apk" $apk_link
 
 	export returncode=$?
 	if [ "$returncode" = "0" ]; then
